"""
Utility constants and helpers shared across the project.
"""
import cv2
import numpy as np

# Scale-bar detection
SCALE_BAR_BLUE_THRESHOLD = 120
SCALE_BAR_BLUE_SCORE_MIN = 60
SCALE_BAR_MIN_SPAN_PX = 8
SCALE_BAR_BGR_DIST_MAX = 16000
SCALE_BAR_DEFAULT_UM = 10.0
SCALE_BAR_ROI_X_RATIO = 0.4
SCALE_BAR_ROI_Y_RATIO = 0.6
SCALE_BAR_ASPECT_RATIO_MIN = 5
SCALE_BAR_ASPECT_RATIO_STRICT = 8
SCALE_BAR_OCR_MATCH_THRESHOLD = 0.4
SCALE_BAR_OCR_EARLY_STOP_SCORE = 0.88
SCALE_BAR_VALUE_RANGE = (0.1, 1000)

# Preprocess defaults
ANALYSIS_BLACKHAT_KERNEL = 31
CALIBRATED_BLUR_KERNEL = 9
CALIBRATED_ADAPTIVE_BLOCK = 11
CALIBRATED_ADAPTIVE_C = 3
PREPROCESS_NOISE_LOW_THRESHOLD = 1.75
PREPROCESS_NOISE_HIGH_THRESHOLD = 2.25
CNT_BRIDGE_STRENGTH_DEFAULT = 0
CNT_BRIDGE_STRENGTH_MAX = 10

# Detection / candidate merging
SKELETON_ANGLE_THRESHOLDS = [160, 150, 140, 130, 120]
SKELETON_WALK_ANGLE_DEG = 150
CNT_MERGE_DISTANCE_DEFAULT_PX = 0
CNT_MERGE_DISTANCE_MAX_PX = 20
CNT_MERGE_MAX_ANGLE_DIFF_DEG = 28.0
CNT_MERGE_MAX_ALIGNMENT_DEG = 32.0

# Uniformity scoring
UNIFORMITY_WEIGHT_CV = 0.35
UNIFORMITY_WEIGHT_AGGLOM = 0.25
UNIFORMITY_WEIGHT_ENTROPY = 0.20
UNIFORMITY_WEIGHT_MORAN = 0.20
UNIFORMITY_LOW_CONFIDENCE_THRESHOLD = 15
UNIFORMITY_VERY_LOW_CONFIDENCE_THRESHOLD = 5
UNIFORMITY_SMALL_SAMPLE_FLOOR = 5
SPATIAL_GRID_MIN_SIZE = 3
SPATIAL_GRID_MAX_SIZE = 15

# Spatial hotspot heuristics
SPATIAL_HOTSPOT_POINT_PERCENTILE = 86.0
SPATIAL_HOTSPOT_COVERAGE_PERCENTILE = 82.0
SPATIAL_HOTSPOT_SHADOW_PERCENTILE = 84.0
SPATIAL_HOTSPOT_POINT_WEIGHT = 0.46
SPATIAL_HOTSPOT_COVERAGE_WEIGHT = 0.20
SPATIAL_HOTSPOT_SHADOW_WEIGHT = 0.34
SPATIAL_HOTSPOT_ACTIVE_SCORE_RANGE_MIN = 0.08
SPATIAL_HOTSPOT_MASK_PERCENTILE_LARGE = 78.0
SPATIAL_HOTSPOT_MASK_PERCENTILE_SMALL = 65.0
SPATIAL_HOTSPOT_SEVERE_PERCENTILE_LARGE = 91.0
SPATIAL_HOTSPOT_SEVERE_PERCENTILE_SMALL = 82.0
SPATIAL_HOTSPOT_OVERLAP_RATIO_THRESHOLD = 0.20
SPATIAL_HOTSPOT_MASK_UPSAMPLE = 12
SPATIAL_HOTSPOT_ABSOLUTE_SCORE_MIN = 0.25

# GUI
DEBOUNCE_DELAY_MS = 150
CHART_REBUILD_DRAW_LIMIT = 24

# Length-distribution export bins
LENGTH_DISTRIBUTION_BINS_UM = [0.0, 5.0, 15.0, 30.0, 40.0, float('inf')]
LENGTH_DISTRIBUTION_LABELS = ['<5μm', '5-15μm', '15-30μm', '30-40μm', '>40μm']

# Long-tube diagnostics
UNIFORMITY_LONG_TUBE_THRESHOLD_UM = 40.0       # 长管长度阈值 (μm)

# Four-part hybrid evaluation defaults (configurable at call site)
EVALUATION_WEIGHT_UNIFORMITY = 0.30
EVALUATION_WEIGHT_THICK_BUNDLE = 0.20
EVALUATION_WEIGHT_LONG_CNT = 0.30
EVALUATION_WEIGHT_AGGLOMERATION = 0.20
EVALUATION_ULTRA_LONG_THRESHOLD_UM = 40.0
EVALUATION_LONG_THICK_WIDTH_THRESHOLD_UM = 1.0
EVALUATION_LONG_CNT_RATIO_EXPONENT = 0.6


def get_length_histogram_bins(lengths: list) -> np.ndarray:
    """Return histogram bins aligned with the exported length distribution."""
    finite_lengths = [float(v) for v in lengths if np.isfinite(v)]
    if not finite_lengths:
        return np.array([0.0, 5.0, 15.0, 30.0, 45.0], dtype=float)

    max_len = max(finite_lengths)
    base_bins = [edge for edge in LENGTH_DISTRIBUTION_BINS_UM if np.isfinite(edge)]
    right_edge = max(base_bins[-1], max_len * 1.05 if max_len > 0 else 45.0)
    bins = np.array(base_bins + [right_edge], dtype=float)
    if bins[-1] <= bins[-2]:
        bins[-1] = bins[-2] + 1.0
    return bins
